sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  global:
language: node_js
node_js:
  - "10"
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - rm -rf docs
  - npm install
  - npm i https://github.com/meta-magic/amexio-ios/blob/v5.21/amexio-ng-extensions.tgz?raw=true
  - ng build --prod
  #- ng build
after_success: 
  - codecov
  #- cp -rf ../docs/* docs/
  #- cp -rf CNAME docs/
  - git add docs
  - git commit -m "[skip travis]  docs-updated"
  - git push  "https://deepali-arvind:${GITHUB_TOKEN}@github.com/meta-magic/amexio-quick-start-app.git" HEAD:master
cache:
  yarn: true
